### ISSUE TITLE
Including library

### ISSUE THREAD

**Issue by ghost** [dzindra/LCDKeypad#1]
Hi,

This may be a simple mistake but I have followed the install instructions on Mac and it returns an error 'does not contain valid library'. I have tried to extract but I cannot get the library to be recognised this way

**Comment by dzindra** [comment]
Hi, I made this library in 2014 for older version of Arduino IDE and there might be some changes, so going to check this. Thanks for pointing this out.

**Comment by ghost** [comment]
Ok thanks -  have managed to manually install now regardless with a bit of adjustment to .cpp file
